'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfUsuarios

    '''<summary>
    '''LiteralEncabezadousuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadousuario As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearusuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearusuario As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadousuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadousuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelusuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelusuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxusuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxusuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxcontrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxcontrasena As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxfecha_expiracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxfecha_expiracion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPerfil As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDevice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''DropDownListEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListEmpresa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LiteralMensajeusuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajeusuario As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarusuarioModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarusuarioModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearusuarioModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearusuarioModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewusuarioList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewusuarioList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxPalabraClaveA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPalabraClaveA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxPalabraClaveB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPalabraClaveB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxPalabraClaveC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPalabraClaveC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Literal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarPalabraClaveModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarPalabraClaveModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearPalabraClaveModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearPalabraClaveModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litHeaderTablaPalabras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeaderTablaPalabras As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''GridViewpalabra_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewpalabra_clave As Global.System.Web.UI.WebControls.GridView
End Class
