'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Conflegislaciones

    '''<summary>
    '''LiteralEncabezadolegislacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadolegislacion As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearlegislacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearlegislacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadolegislacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadolegislacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labellegislacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labellegislacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxlegislacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxlegislacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajelegislacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajelegislacion As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarlegislacionModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarlegislacionModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearlegislacionModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearlegislacionModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewlegislacionList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewlegislacionList As Global.System.Web.UI.WebControls.GridView
End Class
