'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfEmpresas

    '''<summary>
    '''LiteralEncabezadoempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadoempresa As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearempresa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadoempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadoempresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelempresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxempresa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajeempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajeempresa As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarempresaModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarempresaModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearempresaModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearempresaModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewempresaList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewempresaList As Global.System.Web.UI.WebControls.GridView
End Class
