'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfPalabrasClaves

    '''<summary>
    '''LiteralEncabezadopalabra_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadopalabra_clave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearpalabra_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearpalabra_clave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadopalabra_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadopalabra_clave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelpalabra_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelpalabra_clave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxpalabra_clave_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpalabra_clave_a As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxpalabra_clave_b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpalabra_clave_b As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxpalabra_clave_c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpalabra_clave_c As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajepalabra_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajepalabra_clave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarpalabra_claveModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarpalabra_claveModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearpalabra_claveModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearpalabra_claveModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewpalabra_claveList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewpalabra_claveList As Global.System.Web.UI.WebControls.GridView
End Class
