'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfStatus

    '''<summary>
    '''LiteralEncabezadostatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadostatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearstatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadostatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadostatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxstatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajestatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajestatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarstatusModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarstatusModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearstatusModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearstatusModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewstatusList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewstatusList As Global.System.Web.UI.WebControls.GridView
End Class
