'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfTipoCargos

    '''<summary>
    '''LiteralEncabezadotipo_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadotipo_cargo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCreartipo_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreartipo_cargo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadotipo_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadotipo_cargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labeltipo_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labeltipo_cargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxtipo_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxtipo_cargo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajetipo_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajetipo_cargo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizartipo_cargoModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizartipo_cargoModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCreartipo_cargoModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreartipo_cargoModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewtipo_cargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewtipo_cargoList As Global.System.Web.UI.WebControls.GridView
End Class
