'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfPartidos

    '''<summary>
    '''LiteralEncabezadopartido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadopartido As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearpartido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearpartido As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadopartido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadopartido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelpartido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelpartido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxpartido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpartido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxpartidoImagen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpartidoImagen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxpartidoDescCorta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpartidoDescCorta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxpartidoDescLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxpartidoDescLarga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActivo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LiteralMensajepartido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajepartido As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarpartidoModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarpartidoModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearpartidoModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearpartidoModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewpartidoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewpartidoList As Global.System.Web.UI.WebControls.GridView
End Class
