'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfDebates

    '''<summary>
    '''LiteralEncabezadotipo_debate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadotipo_debate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCreartipo_debate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreartipo_debate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadotipo_debate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadotipo_debate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labeltipo_debate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labeltipo_debate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxtipo_debate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxtipo_debate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajetipo_debate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajetipo_debate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizartipo_debateModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizartipo_debateModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCreartipo_debateModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreartipo_debateModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewtipo_debateList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewtipo_debateList As Global.System.Web.UI.WebControls.GridView
End Class
