'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportesSessiones

    '''<summary>
    '''LiteralEncabezadosesiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEncabezadosesiones As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnCrearsesiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearsesiones As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEncabezadosesiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEncabezadosesiones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelsesiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelsesiones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxsesiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxsesiones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxsesiones_corta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxsesiones_corta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxsesiones_larga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxsesiones_larga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxsesiones_fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxsesiones_fecha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LiteralMensajesesiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMensajesesiones As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BtnActualizarsesionesModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarsesionesModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCrearsesionesModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrearsesionesModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewsesionesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewsesionesList As Global.System.Web.UI.WebControls.GridView
End Class
